apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval:     15s 
      evaluation_interval: 15s
    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']
    - job_name: 'node'
      static_configs:
      - targets: ['192.168.3.87:9100', '192.168.3.88:9100', '192.168.3.89:9100', '192.168.3.90:9100', '192.168.3.91:9100', '192.168.3.92:9100']